"""add idempotency key

Revision ID: 8e95dfb4e51d
Revises: c407e6ee1aa1
Create Date: 2026-08-30 22:20:47.268837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e95dfb4e51d'
down_revision: Union[str, Sequence[str], None] = 'c407e6ee1aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('idempotency_key', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'payments', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_column('payments', 'idempotency_key')
    # ### end Alembic commands ###
